baseURL = 'https://blog.cdadoc.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["FixIt", "component-projects"]
defaultContentLanguage = 'zh-cn'

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

[params]
[params.customPartials]
  head = []
  menuDesktop = []
  menuMobile = []
  profile = []
  aside = []
  comment = []
  footer = []
  widgets = []
  assets = [
    "inject/component-projects.html",
  ]
  postTocBefore = []
  postTocAfter = []
  postContentBefore = []
  postContentAfter = []
  postFooterBefore = []
  postFooterAfter = []